wandb_version: 1

Learner:
  desc: null
  value:
    _name: <fastai.learner.Learner object at 0x7f8add91d880>
    arch: levit_128s
    concat_pool: false
    loss_func:
      _name:
        _name: FlattenedLoss of CrossEntropyLoss()
        axis: -1
        flatten: true
        floatify: false
        is_2d: true
      axis: -1
      flatten: true
      floatify: false
      is_2d: true
    lr: 0.001
    metrics:
    - fastai.metrics.error_rate
    - fastai.metrics.accuracy
    model_dir: models
    moms:
    - 0.95
    - 0.85
    - 0.95
    n_out: 11
    normalize: true
    opt_func: fastai.optimizer.Adam
    path: /home/bilal/.fastai/data/paddy
    pretrained: true
    splitter: fastai.vision.learner.default_split
    train_bn: true
    wd: null
    wd_bn_bias: false
MixedPrecision:
  desc: null
  value: true
ParamScheduler:
  desc: null
  value: true
ProgressCallback:
  desc: null
  value: true
Recorder:
  desc: null
  value:
    add_time: true
    train_metrics: false
    valid_metrics: true
TrainEvalCallback:
  desc: null
  value: true
WandbCallback:
  desc: null
  value:
    dataset_name: null
    log: null
    log_dataset: false
    log_model: true
    log_preds: false
    n_preds: 36
    reorder: true
    seed: 12345
    valid_dl: null
_wandb:
  desc: null
  value:
    cli_version: 0.12.18
    framework: fastai
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.9.13
    start_time: 1655498243
    t:
      1:
      - 1
      - 4
      - 5
      - 33
      - 41
      - 49
      - 53
      - 55
      - 63
      2:
      - 1
      - 4
      - 5
      - 33
      - 41
      - 49
      - 53
      - 55
      - 63
      3:
      - 2
      - 16
      4: 3.9.13
      5: 0.12.18
      8:
      - 2
      - 5
batch per epoch:
  desc: null
  value: 346
batch size:
  desc: null
  value: 32
batch_size:
  desc: null
  value: 32
concat_pool:
  desc: null
  value: true
dataset.tfms:
  desc: null
  value: '[Pipeline: PILBase.create, Pipeline: parent_label -> Categorize -- {''vocab'':
    None, ''sort'': True, ''add_na'': False}]'
device:
  desc: null
  value: cuda
dls.after_batch:
  desc: null
  value: 'Pipeline: IntToFloatTensor -- {''div'': 255.0, ''div_mask'': 1}'
dls.after_item:
  desc: null
  value: 'Pipeline: Resize -- {''size'': (224, 224), ''method'': ''squish'', ''pad_mode'':
    ''reflection'', ''resamples'': (<Resampling.BILINEAR: 2>, 0), ''p'': 1.0} -> ToTensor'
dls.before_batch:
  desc: null
  value: 'Pipeline: '
epochs:
  desc: null
  value: 1
frozen:
  desc: null
  value: false
frozen idx:
  desc: null
  value: 0
img_size:
  desc: null
  value: 224
input 1 dim 1:
  desc: null
  value: 32
input 1 dim 2:
  desc: null
  value: 3
input 1 dim 3:
  desc: null
  value: 224
input 1 dim 4:
  desc: null
  value: 224
learning_rate:
  desc: null
  value: 0.001
model parameters:
  desc: null
  value: 7209554
model_name:
  desc: null
  value: levit_128s
n_inp:
  desc: null
  value: 1
num_experiments:
  desc: null
  value: 1
pool:
  desc: null
  value: concat
resize_method:
  desc: null
  value: squish
seed:
  desc: null
  value: 42
split_func:
  desc: null
  value: default
wandb_entity:
  desc: null
  value: bilalcodehub
wandb_project:
  desc: null
  value: paddy-ft
