wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.18
    framework: fastai
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.9.13
    start_time: 1655395776
    t:
      1:
      - 1
      - 4
      - 5
      - 33
      - 41
      - 49
      - 53
      - 55
      - 63
      3:
      - 16
      4: 3.9.13
      5: 0.12.18
      8:
      - 2
      - 5
batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 5
img_size:
  desc: null
  value: 224
learning_rate:
  desc: null
  value: 0.002
model_name:
  desc: null
  value: resnet34
num_experiments:
  desc: null
  value: 1
pool:
  desc: null
  value: concat
resize_method:
  desc: null
  value: crop
seed:
  desc: null
  value: 42
split_func:
  desc: null
  value: default
wandb_entity:
  desc: null
  value: bilalcodehub
wandb_project:
  desc: null
  value: paddy-ft
